version: "3.9"
services:
    flask-app:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        working_dir: /app
        restart: unless-stopped
        ports:
            - 5000:5000
        depends_on:
            - postgres
        volumes:
            - ./:/app

    postgres:
        image: postgres
        container_name: postgres
        restart: unless-stopped
        tty: true
        ports:
            - "5432:5432"
        volumes:
            - ./postgres:/var/lib/postgres
        environment:
            POSTGRES_DB: python_docker
            POSTGRES_USER: posgres
            POSTGRES_PASSWORD: user
